
'use server';

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import sharp from 'sharp';

const ImageGenerationOutputSchema = z.object({
  filename: z.string().describe("The suggested filename for the generated image, ending in .webp, e.g., 'surreal-cat-123.webp'."),
  content: z.string().describe("The generated image as a base64 encoded data URI."),
});
type ImageGenerationOutput = z.infer<typeof ImageGenerationOutputSchema>;

const imageGenerationFlow = ai.defineFlow(
  {
    name: 'imageGenerationFlow',
    inputSchema: z.string(),
    outputSchema: ImageGenerationOutputSchema,
  },
  async (prompt) => {
    const { media } = await ai.generate({
      model: 'googleai/gemini-2.0-flash-preview-image-generation',
      prompt: prompt,
      config: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    });

    if (!media || !media.url) {
      console.error("No media found in the generated message.");
      throw new Error("Image generation failed: No image was returned.");
    }
    
    // Konversi dari data URI ke buffer
    const base64Data = media.url.split(',')[1];
    const imageBuffer = Buffer.from(base64Data, 'base64');
    
    // Proses dengan sharp: ubah ukuran ke 1024x1024 dan kompres ke WebP
    const processedImageBuffer = await sharp(imageBuffer)
        .resize(1024, 1024)
        .webp({ quality: 80 }) // Kualitas 80 adalah keseimbangan yang baik
        .toBuffer();

    // Buat nama file baru dengan ekstensi .webp
    const filename = `${prompt.toLowerCase().replace(/\s+/g, '-').slice(0, 50)}-${Date.now()}.webp`;
    
    // Konversi buffer yang diproses kembali ke data URI
    const processedDataUri = `data:image/webp;base64,${processedImageBuffer.toString('base64')}`;

    return {
      filename,
      content: processedDataUri,
    };    
  }
);


export async function generateImage(prompt: string): Promise<{ success: boolean; data?: ImageGenerationOutput; error?: string }> {
    try {
        const result = await imageGenerationFlow(prompt);
        return { success: true, data: result };
    } catch (error: any) {
        console.error("Error generating image:", error);
        return { success: false, error: error.message };
    }
}

export async function generateJekyllBoilerplate(prompt: string, uid: string, userRole: string): Promise<any> {
  // Placeholder implementation for now.
  // In a real scenario, this would call an AI model to generate the structure.
  console.log(`Generating Jekyll boilerplate for prompt: "${prompt}" (User: ${uid}, Role: ${userRole})`);

  const siteTitle = prompt.split(' ')[0] + ' Site';
  const siteDescription = `A Jekyll site generated by AI based on the prompt: "${prompt}"`;

  return {
    name: siteTitle.toLowerCase().replace(/\s+/g, '-'),
    title: siteTitle,
    description: siteDescription,
    config: {
      title: siteTitle,
      description: siteDescription,
      email: 'your-email@example.com',
      github_username: 'your-github-username',
      twitter_username: 'your-twitter-username',
      markdown: 'kramdown',
      theme: 'minima',
      plugins: ['jekyll-feed', 'jekyll-sitemap', 'jekyll-seo-tag'],
    },
    layouts: [
      { name: 'default', content: '<!-- default layout -->' },
      { name: 'post', content: '<!-- post layout -->' },
      { name: 'page', content: '<!-- page layout -->' },
    ],
    includes: [
      { name: 'header', content: '<!-- header include -->' },
      { name: 'footer', content: '<!-- footer include -->' },
    ],
    posts: [
      {
        title: 'Welcome to AI Generated Jekyll',
        date: new Date().toISOString().split('T')[0],
        content: `This is your first AI-generated post for "${siteTitle}".\n\n${siteDescription}`,
      },
    ],
    pages: [
      { name: 'about', content: 'This is an AI-generated about page.' },
    ],
    collections: {},
    assets: {
      css: '/* AI generated CSS */',
      js: '// AI generated JS',
      images: {},
    },
  };
}
